//
// Created by alexandre on 30/01/2026.
//

#ifndef CRYPTANALYSE_DIFFERENTIELLE_CUSTOMFEISTEL_H
#define CRYPTANALYSE_DIFFERENTIELLE_CUSTOMFEISTEL_H


class CustomFeistel {
};


#endif //CRYPTANALYSE_DIFFERENTIELLE_CUSTOMFEISTEL_H